const Data = [
    {
      id: 1,
      category: "education",
      icon: "icon-graduation",
      year: "Graduation Year : 2023",
      title: "GURU NANAK DEV UNIVERSITY RC JALANDHAR",
      desc: "Electronics & Computer Engineering (pursuing)",
      marks:"8.91 CGPA",
    },
    {
      id: 2,
      category: "education",
      icon: "icon-graduation",
      year: "2018-2019",
      title: "S.V.J.C.D.A.V Public School, Dasuya",
      desc: "XII (Senior Secondary)",
      marks:"Percentage - 92.4%",
    },
    {
      id: 3,
      category: "education",
      icon: "icon-graduation",
      year: "2016-2017",
      title: "S.V.J.C.D.A.V Public School, Dasuya",
      desc: "X  (Secondary)",
      marks:"10 CGPA",
    },
    // {
    //   id: 4,
    //   category: "experience",
    //   icon: "icon-briefcase",
    //   year: "2019 - present",
    //   title: "Web Designer",
    //   desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
    // },
    // {
    //   id: 5,
    //   category: "experience",
    //   icon: "icon-briefcase",
    //   year: "2013 - 2017",
    //   title: "Front-End Developer",
    //   desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
    // },
    // {
    //   id: 6,
    //   category: "experience",
    //   icon: "icon-briefcase",
    //   year: "2009 - 2013",
    //   title: "Back-End Developer",
    //   desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
    // },
  ];
  
export default Data
